name: Automat
on:
  schedule:
    - cron: '0 */8 * * *'  # Exécuter toutes les 8 heures
  workflow_dispatch:  # Permet de lancer manuellement

jobs:
  Update-streams:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout du repo
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Installer les dépendances Python
        run: |
          pip install --upgrade pip
          pip install --no-cache-dir requests selenium selenium-wire webdriver-manager mitmproxy blinker

      - name: Installer Selenium et Chrome
        run: |
          sudo apt update
          sudo apt install -y chromium-chromedriver
  
      - name: Exécuter le script Python pour mettre à jour geral.m3u
        run: python update.py  # Exécute mon script Python

      - name: Update streams PT
        run: bash automatpt.sh  # Ton script existant

      - name: Setup git config
        run: |
          git config user.name "mckfq"
          git config user.email "<>"

      - name: Commit et push
        run: |
          git pull
          git add *.m3u
          git diff --cached --exit-code || (git commit -m "[Auto] Stream update" && git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/mckfq/visual.git main)
