name: Automat
on:
  schedule:
    - cron: '0 */8 * * *'  # Every 8h
  workflow_dispatch:  # Manual lauch

jobs:
  Update-streams:
    runs-on: ubuntu-latest
    steps:
    
      - name: Repository checkout
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Python requests
        run: pip install requests
        
      - name: Install Selenium and Chrome
        run: |
          pip install selenium webdriver-manager
          sudo apt update
          sudo apt install -y chromium-chromedriver
          
      - name: Execute Python and update list
        run: python update.py  # Executing Python script

      - name: Update streams
        run: bash automatpt.sh

      - name: Setup git config
        run: |
          git config user.name "mckfq"
          git config user.email "<>"

      - name: Commit and push
        run: |
          git pull
          git add *.m3u
          git diff --cached --exit-code || (git commit -m "[Auto] Stream update" && git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/mckfq/visual.git main)
