name: Automat
on:
  schedule:
    - cron: '0 */8 * * *' 
  workflow_dispatch:
  
jobs:
  Update-streams:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4

      - name: PT Streams update
        run: bash automatpt.sh

      - name: Git config setup
        run: |
          git config user.name "mckfq"
          git config user.email "<>"

      - name: Commit
        run: |
          git pull
          git add *.m3u
          git diff --cached --exit-code || (git commit -m "[Auto] Stream update" && git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/mckfq/telehub.git main)
