name: Update streams

on:
  schedule:
    - cron: '0 */8 * * *'  # Update every 8h
  workflow_dispatch:  # Manual execute
  
jobs:
  Update-streams:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout
        uses: actions/checkout@v4

      - name: update streams
        run: sh visual/automat.sh

      - name: setup git config
        run: |
          git config user.name "mckfq"
          git config user.email "<>"

      - name: commit
        run: |
          git pull
          cd geral && git add *.m3u
          git commit -m "Update streams"
          git push origin main
