name: Automat
on:
  schedule:
    - cron: '0 */8 * * *'  # Exécuter toutes les 8 heures
  workflow_dispatch:  # Permet de lancer manuellement

jobs:
  Update-streams:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout du repo
        uses: actions/checkout@v4

      - name: Utiliser Python 3.12 (version stable)
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Nettoyer les anciennes installations
        run: |
          pip uninstall -y selenium selenium-wire mitmproxy blinker || true

      - name: Installer les dépendances critiques d'abord
        run: |
          pip install --upgrade pip setuptools wheel
          pip install --no-cache-dir cffi zstandard

      - name: Installer les autres dépendances Python
        run: |
          pip install --no-cache-dir requests selenium selenium-wire==5.1.0 webdriver-manager mitmproxy==10.2.3 blinker

      - name: Installer Google Chrome et ChromeDriver
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable

          # Récupérer la dernière version stable de ChromeDriver depuis l'API officielle
          CHROME_VERSION=$(google-chrome --version | grep -oP '[0-9]+\.[0-9]+\.[0-9]+')
          DRIVER_VERSION=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json" | jq -r ".channels.Stable.downloads.chromedriver[] | select(.platform == \"linux64\") | .url")

          if [[ -z "$DRIVER_VERSION" ]]; then
            echo "❌ Erreur : Impossible de récupérer la version correcte de ChromeDriver."
            exit 1
          fi

          wget -q "$DRIVER_VERSION" -O chromedriver.zip
          unzip -o chromedriver.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Vérification des versions installées
        run: |
          google-chrome --version || echo "⚠️ Google Chrome introuvable"
          chromedriver --version || echo "⚠️ ChromeDriver introuvable"
          python --version

      - name: Exécuter le script Python pour mettre à jour geral.m3u
        run: python update.py  # Exécute mon script Python

      - name: Vérification du fichier geral.m3u
        run: cat geral.m3u || echo "⚠️ Fichier introuvable !"

      - name: Update streams PT
        run: bash automatpt.sh  # Ton script existant

      - name: Setup git config
        run: |
          git config user.name "mckfq"
          git config user.email "<>"

      - name: Commit et push
        run: |
          git pull
          git add *.m3u
          git diff --cached --exit-code || (git commit -m "[Auto] Stream update" && git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/mckfq/visual.git main)
