name: Automat
on:
  schedule:
    - cron: '0 0 * * *'  # Exécute tous les jours à minuit UTC
  workflow_dispatch:

jobs:
  update_list:
    runs-on: ubuntu-latest

    steps:
      - name: Vérifier le dépôt
        uses: actions/checkout@v4

      - name: Configurer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Installer les dépendances critiques d'abord
        run: |
          pip install --upgrade pip setuptools wheel
          pip install --no-cache-dir cffi zstandard blinker==1.6.2

      - name: Installer les autres dépendances Python
        run: |
          pip install --no-cache-dir requests selenium selenium-wire==5.1.0 webdriver-manager mitmproxy==10.2.3

      - name: Exécuter le script Python pour mettre à jour la liste geral.m3u
        run: python update.py

      - name: Vérifier les modifications
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add geral.m3u
          git diff --cached --quiet || git commit -m "Mise à jour automatique de geral.m3u"

      - name: Pousser les modifications
        run: git push
